### ISSUE TITLE
Regexp compilation error (Windows)

### ISSUE THREAD

**Issue by SomeRanDev** [5Mixer/voxel#2]
When running this project, an "Error" popup occurs at startup saying 
```
Regexp compilation error : this version of PCRE2 does not have Unicode support in ^(\w+?)://([\w\.+)(:(\d+))?(/.*)?$
```

My installation went as follows:
* Downloaded this repo
* Ran `git clone https://github.com/Kode/Kha.git`
* Ran `node Kha/make --run` on Windows

I'm using the latest version of Kha, Windows 11, and Haxe v4.3.3

**Comment by 5Mixer** [comment]
Hi! Haven't seen that before unfortunately, and developing this on Linux so it's tricky for me to reproduce what seems likely to be a Windows specific issue.

I had an unrelated native Linux build issue that went away on updating Kha, but that was at the C++ build stage, not runtime. I'm pretty sure I'm not doing anything regex related in this project, but Haxe certainly uses PCRE. I'm on Haxe v4.3.4.

Have other Kha projects build without issue? You could also trying a debug build and running in a debugger.

Finally, you could try HTML5. That works for me (just remember to start the server with `node server/main.js`).

**Comment by SomeRanDev** [comment]
An empty Kha project compiles normally for me. I think I tried HTML5, but could be wrong. And yeah, the PCRE thing seems like an internal Haxe issue? Just wanted to bring it up, if it can't be replicated no biggie, I'll try again later. 😅
